# Generated by Django 5.2.7 on 2025-10-04 08:02

import ckeditor_uploader.fields
import content.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, validators=[content.validators.is_digit]
                    ),
                ),
                ("education_degree", models.CharField(max_length=100)),
                ("study_field", models.CharField(max_length=100)),
                ("education_level", models.CharField(max_length=100)),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes",
                        validators=[content.validators.apply_resume_validate],
                    ),
                ),
                ("cover_letter", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("title_fa", models.CharField(max_length=70, null=True)),
                ("title_en", models.CharField(max_length=70, null=True)),
                ("title_ar", models.CharField(max_length=70, null=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                ("description", models.TextField()),
                ("description_fa", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("description_ar", models.TextField(null=True)),
                ("summary", models.CharField(max_length=100)),
                ("summary_fa", models.CharField(max_length=100, null=True)),
                ("summary_en", models.CharField(max_length=100, null=True)),
                ("summary_ar", models.CharField(max_length=100, null=True)),
                ("body", ckeditor_uploader.fields.RichTextUploadingField()),
                ("body_fa", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("body_en", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("body_ar", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("is_show", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, validators=[content.validators.is_digit]
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("activity_area", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "contact_number",
                    models.CharField(
                        max_length=11, validators=[content.validators.is_digit]
                    ),
                ),
                ("explanation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text_fa", models.CharField(max_length=200)),
                ("text_en", models.CharField(max_length=200)),
                ("text_ar", models.CharField(max_length=200)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.blog"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.comment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("title_fa", models.CharField(max_length=70, null=True)),
                ("title_en", models.CharField(max_length=70, null=True)),
                ("title_ar", models.CharField(max_length=70, null=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                ("description", models.CharField(max_length=100)),
                ("description_fa", models.CharField(max_length=100, null=True)),
                ("description_en", models.CharField(max_length=100, null=True)),
                ("description_ar", models.CharField(max_length=100, null=True)),
                ("dimensions", models.CharField(max_length=30)),
                (
                    "creation_year",
                    models.CharField(
                        max_length=4, validators=[content.validators.is_digit]
                    ),
                ),
                ("scale", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project_gallery")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="content.project",
                    ),
                ),
            ],
        ),
    ]
