# Generated by Django 5.2.7 on 2025-10-07 07:45

import ckeditor_uploader.fields
import content.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "email",
                    models.EmailField(max_length=200, verbose_name="نشانی ایمیل"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[content.validators.is_digit],
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "education_degree",
                    models.CharField(max_length=100, verbose_name="مدرک تحصیلی"),
                ),
                (
                    "study_field",
                    models.CharField(max_length=100, verbose_name="رشته تحصیلی"),
                ),
                (
                    "education_level",
                    models.CharField(max_length=100, verbose_name="مقطع تحصیلی"),
                ),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes",
                        validators=[content.validators.apply_resume_validate],
                        verbose_name="رزومه",
                    ),
                ),
                (
                    "cover_letter",
                    models.CharField(max_length=100, verbose_name="نامه پوششی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "درخواست همکاری",
                "verbose_name_plural": "درخواست\u200cهای همکاری",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="عنوان")),
                (
                    "title_fa",
                    models.CharField(max_length=70, null=True, verbose_name="عنوان"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=70, null=True, verbose_name="عنوان"),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=70, null=True, verbose_name="عنوان"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=70, unique=True, verbose_name="مسیر"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "description_fa",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=100, verbose_name="خلاصه"),
                ),
                (
                    "summary_fa",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="خلاصه"
                    ),
                ),
                (
                    "summary_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="خلاصه"
                    ),
                ),
                (
                    "summary_ar",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="خلاصه"
                    ),
                ),
                (
                    "body",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, verbose_name="متن"
                    ),
                ),
                (
                    "body_fa",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="متن"
                    ),
                ),
                (
                    "body_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="متن"
                    ),
                ),
                (
                    "body_ar",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="متن"
                    ),
                ),
                (
                    "is_show",
                    models.BooleanField(default=False, verbose_name="نشان داده شود؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="عنوان")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "email",
                    models.EmailField(max_length=200, verbose_name="نشانی ایمیل"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[content.validators.is_digit],
                        verbose_name="شماره تماس",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "تماس",
                "verbose_name_plural": "تماس\u200cها",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="دستاورد"
                    ),
                ),
                (
                    "achievement_fa",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="دستاورد"
                    ),
                ),
                (
                    "achievement_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="دستاورد"
                    ),
                ),
                (
                    "achievement_ar",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="دستاورد"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=4,
                        validators=[content.validators.is_digit],
                        verbose_name="سال",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تاریخچه و دستاورد",
                "verbose_name_plural": "تاریخجه و دستاورد ها",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="نام شرکت"),
                ),
                (
                    "activity_area",
                    models.CharField(max_length=100, verbose_name="حوزه فعالیت"),
                ),
                (
                    "email",
                    models.EmailField(max_length=200, verbose_name="نشانی ایمیل"),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=11,
                        validators=[content.validators.is_digit],
                        verbose_name="شماره تماس",
                    ),
                ),
                ("explanation", models.TextField(verbose_name="توضیحات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="published",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "text_fa",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن فارسی"
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن انگلیسی"
                    ),
                ),
                (
                    "text_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن عربی"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fa", "Farsi"), ("ar", "Arabic")],
                        max_length=10,
                        verbose_name="زبان",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.blog",
                        verbose_name="مقاله",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="content.comment",
                        verbose_name="والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="عنوان")),
                (
                    "title_fa",
                    models.CharField(max_length=70, null=True, verbose_name="عنوان"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=70, null=True, verbose_name="عنوان"),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=70, null=True, verbose_name="عنوان"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=70, unique=True, verbose_name="شناسه یکتا"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "description_fa",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, max_length=30, verbose_name="ابعاد"),
                ),
                (
                    "creation_year",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        validators=[content.validators.is_digit],
                        verbose_name="سال ساخت",
                    ),
                ),
                ("scale", models.PositiveIntegerField(default=1, verbose_name="مقیاس")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="project_gallery", verbose_name="تصویر"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="content.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری",
                "verbose_name_plural": "گالری\u200cها",
            },
        ),
    ]
