# Generated by Django 5.2.7 on 2025-10-02 06:29

import submissions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_year',
            field=models.CharField(max_length=4, validators=[submissions.validators.is_digit]),
        ),
    ]
