# Generated by Django 5.2.7 on 2025-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="comment",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fa", "Farsi"), ("ar", "Arabic")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text_ar",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text_fa",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
