# Generated by Django 5.2.7 on 2025-10-05 09:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_comment_updated_at_alter_comment_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="body_ar",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="body_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="body_fa",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description_fa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="summary",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blog",
            name="summary_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="summary_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="summary_fa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_fa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
