# Generated by Django 5.2.7 on 2025-10-05 10:30

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0003_alter_apply_email_alter_blog_body_alter_blog_body_ar_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="creation_year",
            field=models.CharField(
                blank=True, max_length=4, validators=[content.validators.is_digit]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="dimensions",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="project",
            name="scale",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
