# Generated by Django 5.2.7 on 2025-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0004_alter_project_creation_year_alter_project_dimensions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="scale",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
